services:
  _defaults:
    autowire: true

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  Battleship\:
    resource: '../src'

  Battleship\Application:
    public: true
    arguments:
      - !tagged command
